# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 958ac23c216b680c7db9e1c6a8157087975b155307fc14ae471dc62699e1fa69f073a17b58aa004f9cfd5e05e583fdec5a11f2d86807273e3795d1b9d4b780e6

test:
  secret_key_base: 71e62f33f0e91afbfb8711b9a0c3b29aca7e1e229c221e2066c613b56ee1ff30ed9bf3e0277d201174936d05bbc60eca3daaad543f01a5f9b44b3ab536e8d50b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
